/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2015-05-29 03:49:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.myDocument.page.system;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class transCommHideFiled_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	String latestFlag = request.getParameter("latestFlag") == null ? "" :  request.getParameter("latestFlag");

      out.write("\r\n");
      out.write("<input type='hidden' name='taskId' id='taskId' /> \r\n");
      out.write("<input type=hidden id='txnNo' name='txnNo'/>\r\n");
      out.write("<input type=hidden id='tradeNameMvc' name='tradeNameMvc'/>\r\n");
      out.write("<input type=hidden id='butxn_tradeNo' name='butxn_tradeNo'/>\r\n");
      out.write("<input type=hidden id='butxn_blgOrgNo' name='butxn_blgOrgNo'/>\r\n");
      out.write("<input type=hidden id='butxn_tranOrgNo' name='butxn_tranOrgNo'><!--  -->\r\n");
      out.write("<input type=hidden id='butxn_curtBizNo' name='butxn_curtBizNo'/>\r\n");
      out.write("<input type=hidden id='butxn_preBizNo' name='butxn_preBizNo'/>\r\n");
      out.write("<input type=hidden id='butxn_launchModeNo' name='butxn_launchModeNo'/>\r\n");
      out.write("<input type=hidden id='butxn_fileNo' name='butxn_fileNo'/>\r\n");
      out.write("<input type=hidden id='butxn_tranCur' name='butxn_tranCur'/>\r\n");
      out.write("<input type=hidden id='butxn_tranAmt' name='butxn_tranAmt'/>\r\n");
      out.write("<input type=hidden id='butxn_custId' name='butxn_custId'/>\r\n");
      out.write("<input type=hidden id='butxn_managerId' name='butxn_managerId'/>\r\n");
      out.write("<input type=hidden id='butxn_memo' name='butxn_memo'/>\r\n");
      out.write("<input type=hidden id='stepNo' name='stepNo'/>\r\n");
      out.write("<input type=hidden id='chargeHidFieldInfo' name='chargeHidFieldInfo'  /> \r\n");
      out.write("<input type=hidden id='fundsFlowHidFieldInfo' name='fundsFlowHidFieldInfo'  />\r\n");
      out.write("<input type=hidden id='lnloanHidFieldInfo' name='lnloanHidFieldInfo'  />\r\n");
      out.write("<input type=hidden id='sysOperateIdea' name='sysOperateIdea' />\r\n");
      out.write("<input type=hidden id='messageWaitPakctes' name='messageWaitPakctes' />\r\n");
      out.write("<input type=hidden id='swiftVersion' name='swiftVersion' />\r\n");
      out.write("<input type=hidden id='fmtVersion' name='fmtVersion' />\r\n");
      out.write("<input type=hidden id='rtgsVersion' name='rtgsVersion' />\r\n");
      out.write("<input type=hidden id='ediVersion' name='ediVersion' />\r\n");
      out.write("<input type=hidden id='moduleComReport' name='moduleComReport' />\r\n");
      out.write("<input type=hidden id='moduleOpemReport' name='moduleOpemReport' />\r\n");
      out.write("<input type=hidden id='butxn_managerName' name='butxn_managerName'/>\r\n");
      out.write("<input type=hidden id='butxn_blgOrgName' name='butxn_blgOrgName'/>\r\n");
      out.write("<input type=hidden id='butxn_tranTrOrgNo' name='butxn_tranTrOrgNo'>\r\n");
      out.write("<input type=hidden id='butxn_doSupend' name='butxn_doSupend'>\r\n");
      out.write("<input type=hidden id='butxn_corpNo' name='butxn_corpNo' />\r\n");
      out.write("<input type=hidden id='wf_orgno' name='wf_orgno' />\r\n");
      out.write("\r\n");
 
	if(!latestFlag.equals("0")){

      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/myDocument/page/left/left.jsp", out, false);
      out.write('\r');
      out.write('\n');

	}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
