/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2015-05-29 03:49:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.myDocument.page.left;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLDecoder;

public final class left_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 
	String tradeName  = request.getParameter("tradeName")== null ? "" : URLDecoder.decode(request.getParameter("tradeName"),"UTF-8");
	String getTrandUrl = request.getParameter("url") == null ? "" :  request.getParameter("url");
	String tranOrgNo = request.getParameter("butxn_tranOrgNo") == null ? "" : request.getParameter("butxn_tranOrgNo") ;
	String tradeNo = request.getParameter("tradeNo") == null ? "" : request.getParameter("tradeNo") ;
	String isIntergrate = request.getParameter("isIntergrate") == null ? "" :  request.getParameter("isIntergrate");
	String manual = request.getParameter("manual") == null ? "" :  request.getParameter("manual");

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".navbar-inner {\r\n");
      out.write("\tpadding-left: 14px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\theight: 140px;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write(".leftTab .easyui-combobox {\r\n");
      out.write("\twidth: 105.9px !important;\r\n");
      out.write("    height: 25px !important;\r\n");
      out.write("}\r\n");
      out.write(".leftTab .combo-text{\r\n");
      out.write("\twidth:88.9px ;\r\n");
      out.write("}\r\n");
      out.write(".leftTab .combo{\r\n");
      out.write("\tborder: 1px solid #999999;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar tradeName = '");
      out.print(tradeName);
      out.write("';\r\n");
      out.write("\tvar tranOrgNo = '");
      out.print(tranOrgNo);
      out.write("';\r\n");
      out.write("\tvar tradeNo = '");
      out.print(tradeNo);
      out.write("';\r\n");
      out.write("\tvar getTrandUrl = '");
      out.print(getTrandUrl);
      out.write("';\r\n");
      out.write("\tvar isIntergrate ='");
      out.print(isIntergrate);
      out.write("';\r\n");
      out.write("\tvar manual ='");
      out.print(manual);
      out.write("';\r\n");
      out.write("\tvar sysopIdeaOrgName;\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</HEAD>\r\n");
      out.write("\t<div id=\"left\" region=\"west\" data-options=\"split:true\" class=\"plf-dgArea\" style=\"width:235px;\">\r\n");
      out.write("\t\t<div id=\"tradeProperties\" class=\"navbar-inner\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"manageRidSelect\" style=\"overflow:auto;display:none\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"vertical-align: top;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display:inline-block;text-align: left;\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"easyui-datagrid\" style=\"width:380px;height:300px\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-options=\"rownumbers:true,singleSelect:false,title:''\" id=\"leftManageRidTable\">\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<td style=\"vertical-align: top;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display:inline-block;text-align:center;\">\r\n");
      out.write("\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr >\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"vertical-align: top;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"vertical-align: top;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" data-options=\"plain:true\" onclick=\"toRight()\">></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>    \t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"vertical-align: top;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"vertical-align: top;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" data-options=\"plain:true\" onclick=\"toLeft()\"><</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>    \t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t   \t\t\t   </table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"vertical-align: top;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display:inline-block;text-align: right;\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"easyui-datagrid\" style=\"width:380px;height:300px\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-options=\"rownumbers:true,singleSelect:false,title:''\" id=\"rightManageRidTable\">\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
