/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2015-06-11 08:17:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.platform.page.system;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ebills.util.EbillsCfg;
import org.apache.commons.lang.StringUtils;
import java.util.*;
import java.net.*;
import com.eap.core.*;
import org.apache.commons.bussprocess.context.*;
import org.apache.commons.bussprocess.data.*;

public final class excelView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/eap.tld", Long.valueOf(1432547002277L));
    _jspx_dependants.put("/platform/page/system/head.jsp", Long.valueOf(1432546944899L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      com.eap.channel.web.JspContextServices utb = null;
      utb = (com.eap.channel.web.JspContextServices) _jspx_page_context.getAttribute("utb", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (utb == null){
        utb = new com.eap.channel.web.JspContextServices();
        _jspx_page_context.setAttribute("utb", utb, javax.servlet.jsp.PageContext.PAGE_SCOPE);
        out.write('\r');
        out.write('\n');
        out.write('	');

		try {
				utb.initialize(request, response);
		} catch (Exception ex) {
			response.sendRedirect(request.getContextPath()
					+ "/page/session_expire.html");
			return;
		}
	
        out.write('\r');
        out.write('\n');
      }
      out.write('\r');
      out.write('\n');

	Context context = utb.getContext();
	String webAppPath = utb.getWebAppPath();
	String pdfPath = EbillsCfg.getProperty("birt.common.pdf");
	if (null != pdfPath && "" != pdfPath) {
		pdfPath = pdfPath.replace("\\", "/");
	}
	String hostAppPath = "http://"
			+ request.getLocalAddr() + ":"
			+ request.getServerPort() + webAppPath;
	//ç¨æ·ä¸»é¢
	String xcp_sys_usertheme = (String) context.get("userTheme");
	xcp_sys_usertheme = (xcp_sys_usertheme == null || xcp_sys_usertheme
			.equals("")) ? "bootstrap" : xcp_sys_usertheme;
	String EAP_SessionID = utb.getSessionId();
	String xcp_sys_formInitData = "";
	String userId = "";
	String messageOutPut = "";
	try {
		messageOutPut = (String) context.get("messageOutPut");
	} catch (Exception e) {
		System.out.println(e);
	}
	Map<String,String> cfgMap = new HashMap<String, String>();
	try {
		userId = (String) context.getValue("userId");
		xcp_sys_formInitData = (String) context.getValue("initData");
		cfgMap = (Map) context.getValue("cfmMap");
	} catch (Exception e) {
		System.err.println(e);
	}

	String sys_language = (String) context.get("userLanguage");
	String userRptMtd = (String) context.get("userRptMtd");
	String uuidHead = request.getParameter("uuid");
	String taskFlag = request.getParameter("taskFlag");
	String taskState = request.getParameter("taskState");
	String overalParam = request.getParameter("overalParam");

	String sys_workDate = (String) context.get("workDate");

	String latestFlag = request.getParameter("latestFlag") == null
			? ""
			: request.getParameter("latestFlag");
	
	String module_autoTrc = webAppPath + "platform/js/share/autoTrc.js";
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<script>\r\n");
      out.write("\tvar rootPath      = '");
      out.print(webAppPath);
      out.write("';    //æ­¤å¤å®ä¹ç³»ç»çä¸ä¸æwxl\r\n");
      out.write("\tvar hostAppPath   = '");
      out.print(hostAppPath);
      out.write("';   //æå¡å¨çipå ç«¯å£\r\n");
      out.write("\tvar EAP_SID       = '");
      out.print(EAP_SessionID);
      out.write("';\r\n");
      out.write("\tvar EAP_LANGUAGE  = '");
      out.print(sys_language);
      out.write("';  //è®¾ç½®ç³»ç»é»è®¤è¯­è¨\r\n");
      out.write("\tvar xcp_sys_formInitData     = '");
      out.print(xcp_sys_formInitData);
      out.write("'; \r\n");
      out.write("\tvar messageOutPut = '");
      out.print(messageOutPut);
      out.write("';\r\n");
      out.write("\tvar uuidHead      = '");
      out.print(uuidHead);
      out.write("';\r\n");
      out.write("\tvar pdfPath \t  = '");
      out.print(pdfPath);
      out.write("';\r\n");
      out.write("\tvar taskFlag      = '");
      out.print(taskFlag);
      out.write("';\r\n");
      out.write("\tvar taskFlagHadle = false;   //å¤æ­æ¯å¦æ¯æå·¥ç»å\r\n");
      out.write("\t\r\n");
      out.write("\tvar taskState = '");
      out.print(taskState);
      out.write("'; // å¯¹åºå·¥ä½æµæ­¥éª¤    0 å¯æä½ 1æªå®æ 2å·²å®æ\r\n");
      out.write("\t\r\n");
      out.write("\tif(taskState == null || taskState == \"\" || taskState == \"null\"){\r\n");
      out.write("\t\ttaskState = \"0\" ;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(taskState ==\"2\" ){\r\n");
      out.write("\t\ttaskFlag = \"K001\";//å·²ç»å®æ\r\n");
      out.write("\t}\r\n");
      out.write("\tif((taskFlag == null || taskFlag == \"\" || taskFlag == \"null\")){\r\n");
      out.write("\t\ttaskFlag = \"1001\", taskFlagHadle = true;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar overalParam = '");
      out.print(overalParam);
      out.write("';\r\n");
      out.write("\tvar USERID        = '");
      out.print(userId);
      out.write("';\r\n");
      out.write("\tvar sysDate = '");
      out.print(sys_workDate);
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("\tvar xcp_sys_constant_usertheme = '");
      out.print(xcp_sys_usertheme);
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("\tvar latestFlag = '");
      out.print(latestFlag);
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("\tvar USER_RPTMTD = '");
      out.print(userRptMtd);
      out.write("';\r\n");
      out.write("\tif(\"null\" == USER_RPTMTD)USER_RPTMTD == null;\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(webAppPath);
      out.write("platform/js/jquery-core/jquery-1.8.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(webAppPath);
      out.write("platform/js/jquery-core/jquery.cookie.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\ttable.ta_1{width:100%;text-align:center;border-color: floralwhite;border-spacing: 0;border-style: outset;}\r\n");
      out.write("\ttable.ta_1 td tr{text-align:center;table-layout:fixed;}\r\n");
      out.write("\tdiv.display_1{\r\n");
      out.write("\tdisplay:none;}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\tvar pageSize=4;\r\n");
      out.write("\tvar pageNum=1;\r\n");
      out.write("\tvar totalPage = 0;\r\n");
      out.write("\tvar construct = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context.output}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\tvar templateType = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context.templateType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\tvar types = templateType.split(\"&\");\r\n");
      out.write("\tvar data = JSON.parse(construct);\r\n");
      out.write("\tvar html=\"\";\r\n");
      out.write("\ttotalPage = data.totalPages;\r\n");
      out.write("\tvar param = $.cookie(\"param\");\r\n");
      out.write("\tvar html = '<h1>Excel Converter</h1><table class=\"ta_1\" width=\"'+data.result[0].tableWidth+'\" height=\"auto\" border=\"1\">';\r\n");
      out.write("\tvar re = new RegExp(\"\\\\{(.*?)\\\\}\");\r\n");
      out.write("\t$.each(data.result[0].htmlRowStructure, function(i, value) {\r\n");
      out.write("\t\thtml+='<tr valign=\"middle\">';\r\n");
      out.write("\t\t$.each(value.htmlTdStructure,function(j,item){\r\n");
      out.write("\t\t\tvar value = \"\";\r\n");
      out.write("\t\t\tif(!re.test(item.value)){\r\n");
      out.write("\t\t\t\tvalue = item.value;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\thtml+='<td colspan=\"'+item.colspan+'\" rowspan=\"'+item.rowspan+'\" align=\"center\" width=\"'+item.width+'\" height=\"'+item.height+'\">'+value+'</td>'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\thtml+='</tr>';\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("\thtml+=\"</table>\"\r\n");
      out.write("\t$(\"#content\").css(\"width\",data.result[0].tableWidth);\r\n");
      out.write("\t$(\"#bottom\").css(\"width\",data.result[0].tableWidth);\r\n");
      out.write("\t// $(\"#out\").css(\"width\",data.result[0].tableWidth);\r\n");
      out.write("\tvar value = \"当前第\"+1+\"页\"+\"共\"+totalPage+\"页\";\r\n");
      out.write("\t$(\"#pageTail\").html(value);\r\n");
      out.write("\t$(\"#content\").html(html);\r\n");
      out.write("\r\n");
      out.write("\tif(types.length===1){\r\n");
      out.write("\t\tif(types[0]===\"detail\"){\r\n");
      out.write("\t\t\t $(\"#swift\").addClass(\"display_1\");\r\n");
      out.write("\t\t\t $(\"#statisticContent\").addClass(\"display_1\");\r\n");
      out.write("\t\t}else if(types[0]===\"statistic\"){\r\n");
      out.write("\t\t\t $(\"#bottom\").addClass(\"display_1\");\r\n");
      out.write("\t\t\t  $(\"#swift\").addClass(\"display_1\");\r\n");
      out.write("\t\t\t   $(\"content\").addClass(\"display_1\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}else if(types.length===2){\r\n");
      out.write("\t\tif(types[0]===\"detail\"){\r\n");
      out.write("\t\t\t$(\"#statisticContent\").addClass(\"display_1\");\r\n");
      out.write("\t\t}else if(types[0]===\"statistic\"){\r\n");
      out.write("\t\t\t $(\"#bottom\").addClass(\"display_1\");\r\n");
      out.write("\t\t\t $(\"content\").addClass(\"display_1\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tconsole.log(\"无显示方式参数，默认显示所有\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(pageNum>=totalPage){\r\n");
      out.write("\t\t\t$(\"#next\").attr(\"disable\",\"disable\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\tfunction changeButtonType(pageNumber){\r\n");
      out.write("\t\tif(pageNum>=totalPage){\r\n");
      out.write("\t\t\t$(\"#next\").attr(\"disabled\",\"disabled\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#next\").removeAttr(\"disabled\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(pageNum<=1){\r\n");
      out.write("\t\t\t$(\"#back\").attr(\"disabled\",\"disabled\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#back\").removeAttr(\"disabled\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t$(\"#first\").click(function(){\r\n");
      out.write("\t\tpageNum=1;\r\n");
      out.write("\t\tvar value = \"当前第\"+(pageNum)+\"页\"+\"共\"+totalPage+\"页\";\r\n");
      out.write("\t\t$(\"#pageTail\").html(value);\r\n");
      out.write("\t\tgetData(pageNum);\r\n");
      out.write("\t\tchangeButtonType(pageNum);\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#next\").click(function(){\r\n");
      out.write("\t\tpageNum+=1;\r\n");
      out.write("\t\tchangeButtonType(pageNum);\r\n");
      out.write("\t\tvar value = \"当前第\"+(pageNum)+\"页\"+\"共\"+totalPage+\"页\";\r\n");
      out.write("\t\t$(\"#pageTail\").html(value);\r\n");
      out.write("\t\tgetData(pageNum);\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#back\").click(function(){\r\n");
      out.write("\t\tpageNum-=1;\r\n");
      out.write("\t\tchangeButtonType(pageNum);\r\n");
      out.write("\t\tvar value = \"当前第\"+(pageNum)+\"页\"+\"共\"+totalPage+\"页\";\r\n");
      out.write("\t\t$(\"#pageTail\").html(value);\r\n");
      out.write("\t\tgetData(pageNum);\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#last\").click(function(){\r\n");
      out.write("\t\tpageNum=totalPage;\r\n");
      out.write("\t\tvar value = \"当前第\"+(pageNum)+\"页\"+\"共\"+totalPage+\"页\";\r\n");
      out.write("\t\t$(\"#pageTail\").html(value);\r\n");
      out.write("\t\tgetData(pageNum);\r\n");
      out.write("\t\tchangeButtonType(pageNum);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getStatisticData(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype: 'POST',\r\n");
      out.write("\t\t\t\turl: \"./preview.do?method=getMsg&\"+param ,\r\n");
      out.write("\t\t\t\tdata: {\r\n");
      out.write("\t\t\t\t\t\"templateType\" : \"statistic\",\r\n");
      out.write("\t\t\t\t\t\"templateName\":\"test3.xlsx\",\r\n");
      out.write("\t\t\t\t\t\"pageNumber\": 1,\r\n");
      out.write("\t\t\t\t\t\"pageSize\":pageSize\r\n");
      out.write("\t\t\t\t} ,\r\n");
      out.write("\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\tvar data = JSON.parse(data);\r\n");
      out.write("\t\t\t\t\tvar data = data.outEntity;\r\n");
      out.write("\t\t\t\t\tvar statisticHtml = \"\";\r\n");
      out.write("\t\t\t\t\tgenerateHtml(statisticHtml,\"statisticContent\",data);\r\n");
      out.write("\t\t\t\t\t// $(\"#statisticContent\").css(\"width\",data.result[0].tableWidth);\r\n");
      out.write("\t\t\t\t\t// $(\"#statisticContent\").html(statisticHtml);\r\n");
      out.write("\t\t\t\t} ,\r\n");
      out.write("\t\t\t\terror: function(){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"error\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction getData(pageNumber){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype: 'POST',\r\n");
      out.write("\t\t\t\turl: \"./preview.do?method=getMsg&\"+param,\r\n");
      out.write("\t\t\t\tdata: {\r\n");
      out.write("\t\t\t\t\t\"templateType\":\"detail\",\r\n");
      out.write("\t\t\t\t\t\"templateName\": \"test3.xlsx\",\r\n");
      out.write("\t\t\t\t\t\"pageNumber\": pageNumber,\r\n");
      out.write("\t\t\t\t\t\"pageSize\":pageSize\r\n");
      out.write("\t\t\t\t} ,\r\n");
      out.write("\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\tvar data = JSON.parse(data);\r\n");
      out.write("\t\t\t\t\tvar data = data.outEntity;\r\n");
      out.write("\t\t\t\t\ttotalPage = data.totalPages;\r\n");
      out.write("\t\t\t\t\tvar value = \"当前第\"+pageNum+\"页\"+\"共\"+totalPage+\"页\";\r\n");
      out.write("\t\t\t\t\t$(\"#pageTail\").html(value);\r\n");
      out.write("\t\t\t\t\tvar contentHtml=\"\";\r\n");
      out.write("\t\t\t\t\tgenerateHtml(contentHtml,\"content\",data);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#bottom\").css(\"width\",data.result[0].tableWidth);\r\n");
      out.write("\t\t\t\t} ,\r\n");
      out.write("\t\t\t\terror: function(){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"error\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t} \r\n");
      out.write("\tvar type =types[0];\r\n");
      out.write("\t$(\"#statistic\").click(function(){\r\n");
      out.write("\t\tif(type===\"detail\"){\r\n");
      out.write("\t\t\t getStatisticData();\r\n");
      out.write("\t\t\t$(\"#statisticContent\").removeClass(\"display_1\");\r\n");
      out.write("\t\t\t$(\"#statistic\").html(\"切换台账明细表\");\r\n");
      out.write("\t\t\t$(\"#content\").addClass(\"display_1\");\r\n");
      out.write("\t\t\t$(\"#bottom\").addClass(\"display_1\");\r\n");
      out.write("\t\t\ttype=\"statistic\";\r\n");
      out.write("\t\t}else if(type===\"statistic\"){\r\n");
      out.write("\t\t\t getData(pageNum);\r\n");
      out.write("\t\t\t $(\"#statisticContent\").addClass(\"display_1\");\r\n");
      out.write("\t\t\t $(\"#content\").removeClass(\"display_1\");\r\n");
      out.write("\t\t\t $(\"#statistic\").html(\"切换统计信息表\");\r\n");
      out.write("\t\t\t $(\"#bottom\").removeClass(\"display_1\");\r\n");
      out.write("\t\t\t type=\"detail\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction generateHtml(html,statisticContent,data){\r\n");
      out.write("\t\t\tvar html='<h1>Excel Converter</h1><table class=\"ta_1\" width=\"'+data.result[0].tableWidth+'\" height=\"auto\" border=\"1\">';\r\n");
      out.write("\t\t\t\t\t\t$.each(data.result[0].htmlRowStructure, function(i, value) {\r\n");
      out.write("\t\t\t\t\t\t\thtml+='<tr valign=\"middle\">';\r\n");
      out.write("\t\t\t\t\t\t\t$.each(value.htmlTdStructure,function(j,item){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar value = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\tif(!re.test(item.value)){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue = item.value;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\thtml+='<td colspan=\"'+item.colspan+'\" rowspan=\"'+item.rowspan+'\" align=\"center\" width=\"'+item.width+'\" height=\"'+item.height+'\">'+value+'</td>'\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\thtml+='</tr>';\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\thtml+=\"</table>\";\r\n");
      out.write("\t\t\t\t\t\t$(\"#\"+statisticContent).css(\"width\",data.result[0].tableWidth);\r\n");
      out.write("\t\t\t\t\t\t$(\"#\"+statisticContent).html(html);\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<tbody>\r\n");
      out.write("<div style=\"float:left;\" id = \"swift\">\r\n");
      out.write("<button  class=\"btn btn-large\" id=\"statistic\">\r\n");
      out.write("\t\t切换统计表\r\n");
      out.write("</button>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container\" align=\"center\" id=\"out\">\r\n");
      out.write("<div class=\"container\" align=\"center\" id=\"content\">\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container\" align=\"center\" id=\"statisticContent\">\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container\" align=\"center\" id=\"bottom\">\r\n");
      out.write("<button id=\"first\" class=\"btn btn-large\">\r\n");
      out.write("\t\t第一页\r\n");
      out.write("</button>\r\n");
      out.write("<button id=\"back\" class=\"btn btn-large\">\r\n");
      out.write("\t\t上一页\r\n");
      out.write("</button>\r\n");
      out.write("<button id=\"next\" class=\"btn btn-large\">\r\n");
      out.write("\t\t下一页\r\n");
      out.write("</button>\r\n");
      out.write("<button id=\"last\" class=\"btn btn-large\">\r\n");
      out.write("\t\t最后一页\r\n");
      out.write("</button>\r\n");
      out.write("<p id=\"pageTail\"></p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</tbody>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
