/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2015-06-17 01:25:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.platform.page.system;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ebills.util.EbillsCfg;
import org.apache.commons.lang.StringUtils;
import java.util.*;
import java.net.*;
import com.eap.core.*;
import org.apache.commons.bussprocess.context.*;
import org.apache.commons.bussprocess.data.*;

public final class pendingTask_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/eap.tld", Long.valueOf(1432547002277L));
    _jspx_dependants.put("/platform/page/system/head.jsp", Long.valueOf(1432546944899L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      com.eap.channel.web.JspContextServices utb = null;
      utb = (com.eap.channel.web.JspContextServices) _jspx_page_context.getAttribute("utb", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (utb == null){
        utb = new com.eap.channel.web.JspContextServices();
        _jspx_page_context.setAttribute("utb", utb, javax.servlet.jsp.PageContext.PAGE_SCOPE);
        out.write('\r');
        out.write('\n');
        out.write('	');

		try {
				utb.initialize(request, response);
		} catch (Exception ex) {
			response.sendRedirect(request.getContextPath()
					+ "/page/session_expire.html");
			return;
		}
	
        out.write('\r');
        out.write('\n');
      }
      out.write('\r');
      out.write('\n');

	Context context = utb.getContext();
	String webAppPath = utb.getWebAppPath();
	String pdfPath = EbillsCfg.getProperty("birt.common.pdf");
	if (null != pdfPath && "" != pdfPath) {
		pdfPath = pdfPath.replace("\\", "/");
	}
	String hostAppPath = "http://"
			+ request.getLocalAddr() + ":"
			+ request.getServerPort() + webAppPath;
	//ç¨æ·ä¸»é¢
	String xcp_sys_usertheme = (String) context.get("userTheme");
	xcp_sys_usertheme = (xcp_sys_usertheme == null || xcp_sys_usertheme
			.equals("")) ? "bootstrap" : xcp_sys_usertheme;
	String EAP_SessionID = utb.getSessionId();
	String xcp_sys_formInitData = "";
	String userId = "";
	String messageOutPut = "";
	try {
		messageOutPut = (String) context.get("messageOutPut");
	} catch (Exception e) {
		System.out.println(e);
	}
	Map<String,String> cfgMap = new HashMap<String, String>();
	try {
		userId = (String) context.getValue("userId");
		xcp_sys_formInitData = (String) context.getValue("initData");
		cfgMap = (Map) context.getValue("cfmMap");
	} catch (Exception e) {
		System.err.println(e);
	}

	String sys_language = (String) context.get("userLanguage");
	String userRptMtd = (String) context.get("userRptMtd");
	String uuidHead = request.getParameter("uuid");
	String taskFlag = request.getParameter("taskFlag");
	String taskState = request.getParameter("taskState");
	String overalParam = request.getParameter("overalParam");

	String sys_workDate = (String) context.get("workDate");

	String latestFlag = request.getParameter("latestFlag") == null
			? ""
			: request.getParameter("latestFlag");
	
	String module_autoTrc = webAppPath + "platform/js/share/autoTrc.js";
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<script>\r\n");
      out.write("\tvar rootPath      = '");
      out.print(webAppPath);
      out.write("';    //æ­¤å¤å®ä¹ç³»ç»çä¸ä¸æwxl\r\n");
      out.write("\tvar hostAppPath   = '");
      out.print(hostAppPath);
      out.write("';   //æå¡å¨çipå ç«¯å£\r\n");
      out.write("\tvar EAP_SID       = '");
      out.print(EAP_SessionID);
      out.write("';\r\n");
      out.write("\tvar EAP_LANGUAGE  = '");
      out.print(sys_language);
      out.write("';  //è®¾ç½®ç³»ç»é»è®¤è¯­è¨\r\n");
      out.write("\tvar xcp_sys_formInitData     = '");
      out.print(xcp_sys_formInitData);
      out.write("'; \r\n");
      out.write("\tvar messageOutPut = '");
      out.print(messageOutPut);
      out.write("';\r\n");
      out.write("\tvar uuidHead      = '");
      out.print(uuidHead);
      out.write("';\r\n");
      out.write("\tvar pdfPath \t  = '");
      out.print(pdfPath);
      out.write("';\r\n");
      out.write("\tvar taskFlag      = '");
      out.print(taskFlag);
      out.write("';\r\n");
      out.write("\tvar taskFlagHadle = false;   //å¤æ­æ¯å¦æ¯æå·¥ç»å\r\n");
      out.write("\t\r\n");
      out.write("\tvar taskState = '");
      out.print(taskState);
      out.write("'; // å¯¹åºå·¥ä½æµæ­¥éª¤    0 å¯æä½ 1æªå®æ 2å·²å®æ\r\n");
      out.write("\t\r\n");
      out.write("\tif(taskState == null || taskState == \"\" || taskState == \"null\"){\r\n");
      out.write("\t\ttaskState = \"0\" ;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(taskState ==\"2\" ){\r\n");
      out.write("\t\ttaskFlag = \"K001\";//å·²ç»å®æ\r\n");
      out.write("\t}\r\n");
      out.write("\tif((taskFlag == null || taskFlag == \"\" || taskFlag == \"null\")){\r\n");
      out.write("\t\ttaskFlag = \"1001\", taskFlagHadle = true;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar overalParam = '");
      out.print(overalParam);
      out.write("';\r\n");
      out.write("\tvar USERID        = '");
      out.print(userId);
      out.write("';\r\n");
      out.write("\tvar sysDate = '");
      out.print(sys_workDate);
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("\tvar xcp_sys_constant_usertheme = '");
      out.print(xcp_sys_usertheme);
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("\tvar latestFlag = '");
      out.print(latestFlag);
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("\tvar USER_RPTMTD = '");
      out.print(userRptMtd);
      out.write("';\r\n");
      out.write("\tif(\"null\" == USER_RPTMTD)USER_RPTMTD == null;\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"></meta>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(webAppPath);
      out.write("platform/js/jquery-core/jquery-1.8.0.min.js\"></script> \r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(webAppPath);
      out.write("platform/js/share/include.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(webAppPath);
      out.write("myDocument/js/tools/commQueryCondition.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(webAppPath);
      out.write("platform/page/system/pendingTask.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<!-- 为使用公共查询组件方式将原有body id=\"taskList\"修改为pendingTask_sysQueryList -->\r\n");
      out.write("\t<BODY style=\"background: #FFFFFF\" id=\"pendingTask_sysQueryList\" class=\"easyui-layout\" border=false fit=\"true\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 使用公共查询组件方式 begin -->\r\n");
      out.write("\t\t<div id=\"pendingTask_npanel\" region=\"north\" title=\" \" border=\"false\" \r\n");
      out.write("\t\t\tdata-options=\"tools:'#pendingTask_paneltools'\">\r\n");
      out.write("\t\t\t<div id=\"pendingTask_condition\" class='commQueryCondWrap'>\r\n");
      out.write("\t\t\t\t<!-- 查询条件输入区域 -->\r\n");
      out.write("\t\t\t\t<div class='query'>\r\n");
      out.write("\t\t\t\t\t<div class='querybutton'>\r\n");
      out.write("\t\t\t\t\t\t<div class='text'></div>\r\n");
      out.write("\t\t\t\t\t\t<div class='input' id=\"pendingTask_queryDiv\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"pendingTask_cpanel\" region=\"center\" border=\"false\"\r\n");
      out.write("\t\t\tstyle=\"background-color: #FAFAF9;\">\r\n");
      out.write("\t\t\t<table id=\"pendingTask_letterTable\">\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<div id=\"mmm\" class=\"easyui-menu\" style=\"width:120px;\">\r\n");
      out.write("\t\t\t\t<div  id=\"addAnnotation\" data-options=\"iconCls:'icon-add'\">");
      if (_jspx_meth_eap_005flanguage_005f0(_jspx_page_context))
        return;
      out.write("</div>\r\n");
      out.write("\t\t\t\t<div  id=\"viewAnnotation\" data-options=\"iconCls:'icon-view'\">");
      if (_jspx_meth_eap_005flanguage_005f1(_jspx_page_context))
        return;
      out.write("</div>\r\n");
      out.write("\t\t\t\t<div  id=\"gotoHandle\" data-options=\"iconCls:'icon-edit'\">");
      if (_jspx_meth_eap_005flanguage_005f2(_jspx_page_context))
        return;
      out.write("</div>\r\n");
      out.write("\t   \t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id='pendingTask_paneltools' border=\"true\" >\r\n");
      out.write("\t\t\t<div id='pendingTask_commQueryIcon' class='commQueryUpicon'></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 使用公共查询组件方式 end -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t</BODY>\r\n");
      out.write("</HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_eap_005flanguage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f0 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f0.setParent(null);
    // /platform/page/system/pendingTask.jsp(36,63) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f0.setName("pendingTask.addAnnotaion");
    // /platform/page/system/pendingTask.jsp(36,63) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f0.setType("global");
    int _jspx_eval_eap_005flanguage_005f0 = _jspx_th_eap_005flanguage_005f0.doStartTag();
    if (_jspx_th_eap_005flanguage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f0);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f1 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f1.setParent(null);
    // /platform/page/system/pendingTask.jsp(37,65) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f1.setName("pendingTask.viewAnnotaion");
    // /platform/page/system/pendingTask.jsp(37,65) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f1.setType("global");
    int _jspx_eval_eap_005flanguage_005f1 = _jspx_th_eap_005flanguage_005f1.doStartTag();
    if (_jspx_th_eap_005flanguage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f1);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f2 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f2.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f2.setParent(null);
    // /platform/page/system/pendingTask.jsp(38,61) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f2.setName("finishedTask.agreeChange");
    // /platform/page/system/pendingTask.jsp(38,61) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f2.setType("global");
    int _jspx_eval_eap_005flanguage_005f2 = _jspx_th_eap_005flanguage_005f2.doStartTag();
    if (_jspx_th_eap_005flanguage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f2);
    return false;
  }
}
