/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2015-06-17 01:25:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.platform.page.system;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class taskMgr_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/eap.tld", Long.valueOf(1432547002277L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"taskMgrMain_Html\" ></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("   var taskHtml = $(\"#taskMgrMain_Html\");\r\n");
      out.write("   var mgHeight =  ($(window).outerHeight() - 119 )+ \"px\";\r\n");
      out.write("   if(taskHtml.closest(\"#mainCenterArea\").length > 0){\r\n");
      out.write("\t   mgHeight = ($(window).outerHeight() - 119 - 60 ) + \"px\";\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   var strHtml  = '<div id=\"taskMgrMain\" class=\"easyui-tabs\" fit=\"true\" border=\"false\" style=\\'width:'+($(window).outerWidth() - 20)+'px;height:'+mgHeight+';overflow-x:hidden;overflow-y:auto\\'>'+\r\n");
      out.write("\t\t\t\t  '<div id=\"wdrw\" title=\"");
      if (_jspx_meth_eap_005flanguage_005f0(_jspx_page_context))
        return;
      out.write("\" refUrl=\"./pendingTask.do?method=view\" refDataGridId=\"pendingTask_letterTable\">'+\r\n");
      out.write("\t\t\t\t  '\t\t<iframe id=\"taskMgrMain-iframe-a\" src=\"\"  frameborder=\"0\"  style=\"width:100%;height:100%;overflow-x:hidden;overflow-y:auto\"></iframe>'+\r\n");
      out.write("\t\t\t\t  '</div>'+\r\n");
      out.write("\t\t\t\t  '<div id=\"ywcrw\" title=\"");
      if (_jspx_meth_eap_005flanguage_005f1(_jspx_page_context))
        return;
      out.write("\" refurl =\"./pendingTask.do?method=viewdo\" refDataGridId=\"currentTask_letterTable\">'+\r\n");
      out.write("\t\t\t\t  '\t<iframe id=\"taskMgrMain-iframe-b\" src=\"\" frameborder=\"0\"  style=\"width:100%;height:100%;overflow-x:hidden;overflow-y:auto\"></iframe>'+\r\n");
      out.write("\t\t\t\t  '</div>'+\r\n");
      out.write("\t\t\t\t  '</div>';\r\n");
      out.write("\r\n");
      out.write("    taskHtml.html(strHtml);\r\n");
      out.write("\t$('#wdrw').attr('title',$xcp.i18n(\"sys.mytask\"));\r\n");
      out.write("\t$('#ywcrw').attr('title',$xcp.i18n(\"sys.finish\"));\r\n");
      out.write("\t$.parser.parse(taskHtml);\r\n");
      out.write("\t\r\n");
      out.write("   $(\"#taskMgrMain\").tabs({\r\n");
      out.write("\t   border:false,\r\n");
      out.write("\t   onSelect:function(title){\r\n");
      out.write("\t\t   var panel =  $(\"#taskMgrMain\").tabs('getTab',title);\r\n");
      out.write("\t\t   var url   = $(panel).attr('refUrl'); \r\n");
      out.write("\t\t   var iframeSrc = $(panel).find('iframe').attr(\"src\");\r\n");
      out.write("\t\t   top.window.onbeforeunload = null;\r\n");
      out.write("\t\t   if(url && iframeSrc == ''){\r\n");
      out.write("\t\t\t   $(panel).find('iframe').attr(\"src\",$xcp.def.getFullUrl(url) + \"&uuid=mainPageTaskMgr\");\r\n");
      out.write("\t\t   }else{\r\n");
      out.write("\t\t\t   var dagaGridId =  $(panel).attr('refDataGridId'); \r\n");
      out.write("\t\t\t   var dwindw = $(panel).find('iframe')[0].contentWindow;\r\n");
      out.write("\t\t\t   if(dwindw.$(\"#\" + dagaGridId).length>0){\r\n");
      out.write("\t\t\t\t   dwindw.$(\"#\" + dagaGridId).datagrid('reload');\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t   }\r\n");
      out.write("   });\r\n");
      out.write("   $(\"#taskMgrMain-iframe-a\").attr(\"src\",$xcp.def.getFullUrl(\"./pendingTask.do?method=view\") + \"&uuid=mainPageTaskMgr\");\r\n");
      out.write("   \r\n");
      out.write("   $(function(){\r\n");
      out.write("\t   $(window).resize(function(){\r\n");
      out.write("\t\t   var taskMgrMain = $(\"#taskMgrMain\");\r\n");
      out.write("\t\t   taskMgrMain.css({\r\n");
      out.write("\t\t\t   height : ($(window).outerHeight() - 119  )\r\n");
      out.write("\t\t   }).tabs(\"resize\");\r\n");
      out.write("\t\t});\r\n");
      out.write("   });\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_eap_005flanguage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f0 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f0.setParent(null);
    // /platform/page/system/taskMgr.jsp(36,29) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f0.setName("main.woderw");
    // /platform/page/system/taskMgr.jsp(36,29) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f0.setType("main");
    int _jspx_eval_eap_005flanguage_005f0 = _jspx_th_eap_005flanguage_005f0.doStartTag();
    if (_jspx_th_eap_005flanguage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f0);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f1 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f1.setParent(null);
    // /platform/page/system/taskMgr.jsp(39,30) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f1.setName("main.yiwcrw");
    // /platform/page/system/taskMgr.jsp(39,30) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f1.setType("main");
    int _jspx_eval_eap_005flanguage_005f1 = _jspx_th_eap_005flanguage_005f1.doStartTag();
    if (_jspx_th_eap_005flanguage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f1);
    return false;
  }
}
