/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2015-05-29 03:44:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.platform.page.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.eap.core.*;
import org.apache.commons.bussprocess.data.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/eap.tld", Long.valueOf(1432547002277L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      com.eap.channel.web.JspContextServices utb = null;
      utb = (com.eap.channel.web.JspContextServices) _jspx_page_context.getAttribute("utb", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (utb == null){
        utb = new com.eap.channel.web.JspContextServices();
        _jspx_page_context.setAttribute("utb", utb, javax.servlet.jsp.PageContext.PAGE_SCOPE);
        out.write('\r');
        out.write('\n');
        out.write('	');

		try {
				utb.initialize(request, response);
			} catch (Exception ex) {
				response.sendRedirect(request.getContextPath()
						+ "/platform/page/main/session_expire.html");
				return;
			}
	int login = -1;
	if(request.getAttribute("login") != null){
		login = (Integer) request.getAttribute("login");
	}
	/* if(login != 3){
		Cookie cookie = new Cookie("EAP_SID", "");
		cookie.setMaxAge(0);
		response.addCookie(cookie);
	} */
	
        out.write('\r');
        out.write('\n');
      }
      out.write('\r');
      out.write('\n');

	String errorMes = "", errorCode = "" , userCode = "";
	try {
		errorMes = (String) request.getAttribute("errorMessage");
		errorCode = (String) request.getAttribute("errorCode");
		userCode = (String) request.getAttribute("userCode");
		userCode = (userCode == "null" || userCode == null ) ? "" : userCode;
	} catch (Exception ex) {
	}
	errorMes = errorMes == null || errorMes == "SYSERROR" ? ""
			: errorMes;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>");
      if (_jspx_meth_eap_005flanguage_005f0(_jspx_page_context))
        return;
      out.write("</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<meta http-equiv=\"Pragma\" content=\"no-cache\" />\r\n");
      out.write("<meta http-equiv=\"Cache-Control\" content=\"no-cache\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./platform/css/gjjs-themes/default/login.css\"></link>\r\n");
      out.write("\r\n");
      out.write("<script src=\"platform/js/jquery-core/jquery-1.8.0.min.js\"></script>\r\n");
      out.write("<script src=\"platform/js/share/md5.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" \tvar userCode = '");
      out.print(userCode);
      out.write("';//登陆的用户id 方便密码错误后记录账号\r\n");
      out.write(" \tvar errCode  = '");
      out.print(errorCode);
      out.write("';//错误信息 根据错误code设计焦点\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"./platform/page/main/index.js\"></script>\r\n");

if(errorCode != null && "EBP-101".equals(errorCode)){
	String outScript = "<script>eval(duplicateLogin('"+ request.getContextPath() +"'));</script>";
	out.print(outScript);
}

      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"loginbg\">\r\n");
      out.write("\t\t<form method=\"post\" action=\"./signIn.do\" name=\"form2\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"usr_language\" name=\"usr_language\" />\r\n");
      out.write("\t\t\t<div style=\"display:none\">\r\n");
      out.write("           <input type=\"password\" id=\"hidePass\" name=\"hidePass\" />\r\n");
      out.write("           </div>\r\n");
      out.write("\t\t\t<div class=\"banner_bg\">Login</div>\r\n");
      out.write("\t\t\t<div class=\"login\" >\r\n");
      out.write("\t\t\t\t<div class=\"logo\" ></div>\r\n");
      out.write("\t\t\t\t<div id=\"main\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div><span id=\"logShow\"\r\n");
      out.write("\t\t\t\t\tstyle=\"color: red; line-height: 18px; padding-left: 10px; padding-right: 85px; margin-left: 1px; font-size: 14px;\">");
      out.print(errorMes);
      out.write("</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"button loginBtn\" id=\"loginBtn\">登   录</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_eap_005flanguage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f0 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f0.setParent(null);
    // /platform/page/main/index.jsp(41,7) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f0.setName("main.title");
    // /platform/page/main/index.jsp(41,7) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f0.setType("main");
    int _jspx_eval_eap_005flanguage_005f0 = _jspx_th_eap_005flanguage_005f0.doStartTag();
    if (_jspx_th_eap_005flanguage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f0);
    return false;
  }
}
