/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2015-05-29 03:44:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.platform.page.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ebills.util.EbillsCfg;
import org.apache.commons.lang.StringUtils;
import java.util.*;
import java.net.*;
import com.eap.core.*;
import org.apache.commons.bussprocess.context.*;
import org.apache.commons.bussprocess.data.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/eap.tld", Long.valueOf(1432547002277L));
    _jspx_dependants.put("/platform/page/system/head.jsp", Long.valueOf(1432546944899L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      com.eap.channel.web.JspContextServices utb = null;
      utb = (com.eap.channel.web.JspContextServices) _jspx_page_context.getAttribute("utb", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (utb == null){
        utb = new com.eap.channel.web.JspContextServices();
        _jspx_page_context.setAttribute("utb", utb, javax.servlet.jsp.PageContext.PAGE_SCOPE);
        out.write('\r');
        out.write('\n');
        out.write('	');

		try {
				utb.initialize(request, response);
		} catch (Exception ex) {
			response.sendRedirect(request.getContextPath()
					+ "/page/session_expire.html");
			return;
		}
	
        out.write('\r');
        out.write('\n');
      }
      out.write('\r');
      out.write('\n');

	Context context = utb.getContext();
	String webAppPath = utb.getWebAppPath();
	String pdfPath = EbillsCfg.getProperty("birt.common.pdf");
	if (null != pdfPath && "" != pdfPath) {
		pdfPath = pdfPath.replace("\\", "/");
	}
	String hostAppPath = "http://"
			+ request.getLocalAddr() + ":"
			+ request.getServerPort() + webAppPath;
	//ç¨æ·ä¸»é¢
	String xcp_sys_usertheme = (String) context.get("userTheme");
	xcp_sys_usertheme = (xcp_sys_usertheme == null || xcp_sys_usertheme
			.equals("")) ? "bootstrap" : xcp_sys_usertheme;
	String EAP_SessionID = utb.getSessionId();
	String xcp_sys_formInitData = "";
	String userId = "";
	String messageOutPut = "";
	try {
		messageOutPut = (String) context.get("messageOutPut");
	} catch (Exception e) {
		System.out.println(e);
	}
	Map<String,String> cfgMap = new HashMap<String, String>();
	try {
		userId = (String) context.getValue("userId");
		xcp_sys_formInitData = (String) context.getValue("initData");
		cfgMap = (Map) context.getValue("cfmMap");
	} catch (Exception e) {
		System.err.println(e);
	}

	String sys_language = (String) context.get("userLanguage");
	String userRptMtd = (String) context.get("userRptMtd");
	String uuidHead = request.getParameter("uuid");
	String taskFlag = request.getParameter("taskFlag");
	String taskState = request.getParameter("taskState");
	String overalParam = request.getParameter("overalParam");

	String sys_workDate = (String) context.get("workDate");

	String latestFlag = request.getParameter("latestFlag") == null
			? ""
			: request.getParameter("latestFlag");
	
	String module_autoTrc = webAppPath + "platform/js/share/autoTrc.js";
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<script>\r\n");
      out.write("\tvar rootPath      = '");
      out.print(webAppPath);
      out.write("';    //æ­¤å¤å®ä¹ç³»ç»çä¸ä¸æwxl\r\n");
      out.write("\tvar hostAppPath   = '");
      out.print(hostAppPath);
      out.write("';   //æå¡å¨çipå ç«¯å£\r\n");
      out.write("\tvar EAP_SID       = '");
      out.print(EAP_SessionID);
      out.write("';\r\n");
      out.write("\tvar EAP_LANGUAGE  = '");
      out.print(sys_language);
      out.write("';  //è®¾ç½®ç³»ç»é»è®¤è¯­è¨\r\n");
      out.write("\tvar xcp_sys_formInitData     = '");
      out.print(xcp_sys_formInitData);
      out.write("'; \r\n");
      out.write("\tvar messageOutPut = '");
      out.print(messageOutPut);
      out.write("';\r\n");
      out.write("\tvar uuidHead      = '");
      out.print(uuidHead);
      out.write("';\r\n");
      out.write("\tvar pdfPath \t  = '");
      out.print(pdfPath);
      out.write("';\r\n");
      out.write("\tvar taskFlag      = '");
      out.print(taskFlag);
      out.write("';\r\n");
      out.write("\tvar taskFlagHadle = false;   //å¤æ­æ¯å¦æ¯æå·¥ç»å\r\n");
      out.write("\t\r\n");
      out.write("\tvar taskState = '");
      out.print(taskState);
      out.write("'; // å¯¹åºå·¥ä½æµæ­¥éª¤    0 å¯æä½ 1æªå®æ 2å·²å®æ\r\n");
      out.write("\t\r\n");
      out.write("\tif(taskState == null || taskState == \"\" || taskState == \"null\"){\r\n");
      out.write("\t\ttaskState = \"0\" ;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(taskState ==\"2\" ){\r\n");
      out.write("\t\ttaskFlag = \"K001\";//å·²ç»å®æ\r\n");
      out.write("\t}\r\n");
      out.write("\tif((taskFlag == null || taskFlag == \"\" || taskFlag == \"null\")){\r\n");
      out.write("\t\ttaskFlag = \"1001\", taskFlagHadle = true;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar overalParam = '");
      out.print(overalParam);
      out.write("';\r\n");
      out.write("\tvar USERID        = '");
      out.print(userId);
      out.write("';\r\n");
      out.write("\tvar sysDate = '");
      out.print(sys_workDate);
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("\tvar xcp_sys_constant_usertheme = '");
      out.print(xcp_sys_usertheme);
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("\tvar latestFlag = '");
      out.print(latestFlag);
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("\tvar USER_RPTMTD = '");
      out.print(userRptMtd);
      out.write("';\r\n");
      out.write("\tif(\"null\" == USER_RPTMTD)USER_RPTMTD == null;\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

Integer login = 0;
Integer timeOutDays = -1;
if(request.getAttribute("login") != null){
	login = (Integer)request.getAttribute("login");
	if(login == 0){
		if(request.getAttribute("timeOutDays") != null){
			timeOutDays = (Integer)request.getAttribute("timeOutDays");
		}
	}
}
String printRole = "false";
if(request.getAttribute("login") != null){
	login = (Integer)request.getAttribute("login");
	if(login == 0){
		if(request.getAttribute("printRole") != null){
			printRole = (String)request.getAttribute("printRole");
		}
	}
} else {
	if(request.getAttribute("printRole") != null){
		printRole = (String)request.getAttribute("printRole");
	}
}

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar usrLogin = '");
      out.print(login);
      out.write("';\r\n");
      out.write("\tvar timeOutDays = '");
      out.print(timeOutDays);
      out.write("';\r\n");
      out.write("\tvar printRole = '");
      out.print(printRole);
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("\tfunction initApplet(){\r\n");
      out.write("\t\t//var str = '<applet code=\"AppletTest.class\" id=\"AppletTest\" name = \"AppletTest\" codebase=\"./\" archive=\"'+rootPath+'/report/printTest.jar\"></applet>';\r\n");
      out.write("\t\tif(printRole == 'true'){\r\n");
      out.write("\t\t\tvar str = '';\r\n");
      out.write("\t\t\tif ($.browser.msie ) {\r\n");
      out.write("\t\t\t\tstr+='<object id=\"AppletTest\" name = \"AppletTest\" classid=\"clsid:8AD9C840-044E-11D1-B3E9-00805F499D93\" ';\r\n");
      out.write("\t\t\t\tstr+='\tcodebase=\"");
      out.print(hostAppPath);
      out.write("/report/jre-6u37-windows-i586.exe\" height=0 width=0>';\r\n");
      out.write("\t\t\t\tstr+='\t<PARAM NAME=\"code\" VALUE=\"AppletTest.class\">';\r\n");
      out.write("\t\t\t\tstr+='\t<PARAM NAME=\"id\" VALUE=\"AppletTest\">';\r\n");
      out.write("\t\t\t\tstr+='\t<PARAM NAME=\"name\" VALUE=\"AppletTest\">';\r\n");
      out.write("\t\t\t\tstr+='\t<PARAM NAME=\"CODEBASE\" VALUE=\"./\">';\r\n");
      out.write("\t\t\t\tstr+='\t<PARAM NAME=\"ARCHIVE\" VALUE=\"'+rootPath+'/report/printTest.jar\">';\r\n");
      out.write("\t\t\t\tstr+='\t<param name=\"type\" value=\"application/x-java-applet;version=1.6\">';\r\n");
      out.write("\t\t\t\tstr+='\t<param name=\"scriptable\" value=\"false\">';\r\n");
      out.write("\t\t\t\tstr+='</object>';\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tstr += '<applet code=\"AppletTest.class\" id=\"AppletTest\" name = \"AppletTest\" codebase=\"./\" archive=\"'+rootPath+'/report/printTest.jar\"></applet>';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(str).appendTo('body');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<TITLE>");
      if (_jspx_meth_eap_005flanguage_005f0(_jspx_page_context))
        return;
      out.write("</TITLE>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"></meta>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"./platform/css/gjjs-themes/");
      out.print(xcp_sys_usertheme);
      out.write("/main.css\"></link>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"./platform/js/jquery-core/jquery-1.8.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./platform/js/share/include.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./platform/js/share/md5.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./platform/js/share/tools.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./platform/js/share/app.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./myDocument/js/tools/print.js\"></script>\r\n");
      out.write("<script>\t\r\n");
      out.write("\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t$('body').xcpApp();\r\n");
      out.write("\t\t\t\t//$xcp.toolsMgr.loadPrintSetting();\r\n");
      out.write("\t\t\t\tvar sysDate1 = sysDate.replace(\"-\",\"年\");\r\n");
      out.write("\t\t\t\tsysDate1 = sysDate1.replace(\"-\",\"月\");\r\n");
      out.write("\t\t\t\tsysDate1 +=\"日\"; \r\n");
      out.write("\t\t\t    var\tworkDate = \"<font size=\\\"12px\\\" style='font-family: Tahoma, Arial, \\\"宋体\\\";'>\"+(\"日期:\")+\"</font>\"+\"<font style=\\\"color:#0073ea; cursor:pointer\\\">\"+(sysDate1)+\"</font>\";\r\n");
      out.write("\t\t\t\t$('.workDate').html(workDate);\r\n");
      out.write("\t\t\t});\t\t\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"easyui-layout \">\r\n");
      out.write("\t<div region=\"center\" style=\"overflow: hidden;\">\r\n");
      out.write("\t\t<div class='mainTop'>\r\n");
      out.write("\t\t\t<div class=\"logo\"></div>\r\n");
      out.write("\t\t\t<div class='welcome'>\r\n");
      out.write("\t\t\t\t<div id='userLoginInfo'></div>\r\n");
      out.write("\t\t\t\t<div class='modPassword'></div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class='workDate'></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class='rightToolsArea'>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t\t<div id='desktopMoreMenu' class=\"icon_sys\" refId='sysMasterMenu'\r\n");
      out.write("\t\t\t\t\ttitle='");
      if (_jspx_meth_eap_005flanguage_005f1(_jspx_page_context))
        return;
      out.write("'></div>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t<div id='desktopSetting' class=\"icon_setting\"\r\n");
      out.write("\t\t\t\t\trefId='sysUserDefSetting'\r\n");
      out.write("\t\t\t\t\ttitle='");
      if (_jspx_meth_eap_005flanguage_005f2(_jspx_page_context))
        return;
      out.write("'></div>\r\n");
      out.write("\t\t\t\t<div class=\"icon_help\"\r\n");
      out.write("\t\t\t\t\ttitle='");
      if (_jspx_meth_eap_005flanguage_005f3(_jspx_page_context))
        return;
      out.write("'></div>\r\n");
      out.write("\t\t\t\t<div id='userSysExit' class=\"icon_exit\"\r\n");
      out.write("\t\t\t\t\ttitle='");
      if (_jspx_meth_eap_005flanguage_005f4(_jspx_page_context))
        return;
      out.write("'></div>\r\n");
      out.write("\t\t\t\t<!-- title= ");
      if (_jspx_meth_eap_005flanguage_005f5(_jspx_page_context))
        return;
      out.write(" -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class='mainTopSplit'></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"mainCenterArea\" class=\"mainCenter\">\r\n");
      out.write("\t\t\t<div id='defMasterMenuIconAreaWrap' class='defMasterMenuIconAreaWrap'>\r\n");
      out.write("\t\t\t\t<div class='arrow menuDown'></div>\r\n");
      out.write("\t\t\t\t<!-- 默认有一个菜单页签 -->\r\n");
      out.write("\t\t\t\t<!-- <div id='MasterMenuIconArea-1' class='defMasterMenuIconArea current'></div> -->\r\n");
      out.write("\t\t\t\t<div class='arrow menuUp'></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"defMasterMenuNavigation\">\r\n");
      out.write("\t\t\t\t<!-- <div id='MasterMenuNavigation-1' class='iconNavigation current'  refIconAreaId='MasterMenuIconArea-1'>\r\n");
      out.write("\t\t\t\t    </div> -->\r\n");
      out.write("\t\t\t\t<div id=\"masterMenuDel\" class=\"masterMenuDel\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"masterMenuAdd\" class=\"masterMenuAdd\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"masterMenuUpdate\" class=\"masterMenuUpdate\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"masterMenuOk\" class=\"masterMenuOk\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div region=\"south\" style=\"height: 34px; overflow: hidden;\">\r\n");
      out.write("\t\t<div class='mainFooter'>\r\n");
      out.write("\t\t\t<div id='taskStart' class='start'></div>\r\n");
      out.write("\t\t\t<div id='taskBars' class='taskBars'></div>\r\n");
      out.write("\t\t\t<div id='taskRight' class='taskRight'>\r\n");
      out.write("\t\t\t\t<div class=\"fengX\"></div>\r\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/platform/page/system/widgets/taskWidgets.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id='sysMasterMenu' class='toolNavigation'>\r\n");
      out.write("\t\t<div class='arrowhead'></div>\r\n");
      out.write("\t\t<div class='contentWrap'>\r\n");
      out.write("\t\t\t<div class='tabsWrap'>\r\n");
      out.write("\t\t\t\t<div class='tab business' refId='menu_business_content'>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_eap_005flanguage_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class='tab parameter' refId='menu_parameter_content'>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_eap_005flanguage_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t<div class='tab statement' refId='menu_statement_content'>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_eap_005flanguage_005f8(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class='close'></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class='content'>\r\n");
      out.write("\t\t\t\t<div class='tabRefContent' id='menu_business_content'\r\n");
      out.write("\t\t\t\t\tsysMenuType='BU'></div>\r\n");
      out.write("\t\t\t\t<div class='tabRefContent' id='menu_parameter_content'\r\n");
      out.write("\t\t\t\t\tsysMenuType='PB'></div>\r\n");
      out.write("\t\t\t\t<!-- <div class='tabRefContent' id='menu_declare_content'    sysMenuType ='DL'></div> -->\r\n");
      out.write("\t\t\t\t<div class='tabRefContent' id='menu_statement_content'\r\n");
      out.write("\t\t\t\t\tsysMenuType='RP'></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id='sysUserDefSetting' class='toolNavigation'>\r\n");
      out.write("\t\t<div class='arrowhead'></div>\r\n");
      out.write("\t\t<div class='contentWrap'>\r\n");
      out.write("\t\t\t<div class='qpHead'>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_eap_005flanguage_005f9(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t<div class='close'></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class='content'>\r\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/platform/page/system/widgets/userSetting.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/platform/page/system/widgets/defIconCls.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<form id=\"userLangOrThemeDefForm\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"usr_language\" name=\"usr_language\" /> <input\r\n");
      out.write("\t\t\ttype=\"hidden\" id=\"usr_theme\" name=\"usr_theme\" /> <input type=\"hidden\"\r\n");
      out.write("\t\t\tid=\"usr_viewRptMtd\" name=\"usr_viewRptMtd\" /> <input type=\"hidden\"\r\n");
      out.write("\t\t\tid=\"user_quickBar\" name=\"user_quickBar\" />\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_eap_005flanguage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f0 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f0.setParent(null);
    // /platform/page/main/main.jsp(58,7) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f0.setName("main.title");
    // /platform/page/main/main.jsp(58,7) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f0.setType("main");
    int _jspx_eval_eap_005flanguage_005f0 = _jspx_th_eap_005flanguage_005f0.doStartTag();
    if (_jspx_th_eap_005flanguage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f0);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f1 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f1.setParent(null);
    // /platform/page/main/main.jsp(95,12) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f1.setName("main.xintcd");
    // /platform/page/main/main.jsp(95,12) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f1.setType("main");
    int _jspx_eval_eap_005flanguage_005f1 = _jspx_th_eap_005flanguage_005f1.doStartTag();
    if (_jspx_th_eap_005flanguage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f1);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f2 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f2.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f2.setParent(null);
    // /platform/page/main/main.jsp(100,12) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f2.setName("main.changysz");
    // /platform/page/main/main.jsp(100,12) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f2.setType("main");
    int _jspx_eval_eap_005flanguage_005f2 = _jspx_th_eap_005flanguage_005f2.doStartTag();
    if (_jspx_th_eap_005flanguage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f2);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f3 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f3.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f3.setParent(null);
    // /platform/page/main/main.jsp(102,12) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f3.setName("main.bangz");
    // /platform/page/main/main.jsp(102,12) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f3.setType("main");
    int _jspx_eval_eap_005flanguage_005f3 = _jspx_th_eap_005flanguage_005f3.doStartTag();
    if (_jspx_th_eap_005flanguage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f3);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f4 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f4.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f4.setParent(null);
    // /platform/page/main/main.jsp(104,12) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f4.setName("main.tuic");
    // /platform/page/main/main.jsp(104,12) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f4.setType("main");
    int _jspx_eval_eap_005flanguage_005f4 = _jspx_th_eap_005flanguage_005f4.doStartTag();
    if (_jspx_th_eap_005flanguage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f4);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f5 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f5.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f5.setParent(null);
    // /platform/page/main/main.jsp(105,16) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f5.setName("lc.issueDate");
    // /platform/page/main/main.jsp(105,16) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f5.setType("main");
    int _jspx_eval_eap_005flanguage_005f5 = _jspx_th_eap_005flanguage_005f5.doStartTag();
    if (_jspx_th_eap_005flanguage_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f5);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f6 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f6.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f6.setParent(null);
    // /platform/page/main/main.jsp(156,5) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f6.setName("main.yew");
    // /platform/page/main/main.jsp(156,5) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f6.setType("main");
    int _jspx_eval_eap_005flanguage_005f6 = _jspx_th_eap_005flanguage_005f6.doStartTag();
    if (_jspx_th_eap_005flanguage_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f6);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f7 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f7.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f7.setParent(null);
    // /platform/page/main/main.jsp(159,5) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f7.setName("main.cans");
    // /platform/page/main/main.jsp(159,5) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f7.setType("main");
    int _jspx_eval_eap_005flanguage_005f7 = _jspx_th_eap_005flanguage_005f7.doStartTag();
    if (_jspx_th_eap_005flanguage_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f7);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f8 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f8.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f8.setParent(null);
    // /platform/page/main/main.jsp(163,5) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f8.setName("main.baob");
    // /platform/page/main/main.jsp(163,5) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f8.setType("main");
    int _jspx_eval_eap_005flanguage_005f8 = _jspx_th_eap_005flanguage_005f8.doStartTag();
    if (_jspx_th_eap_005flanguage_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f8);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f9 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f9.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f9.setParent(null);
    // /platform/page/main/main.jsp(192,4) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f9.setName("main.changysz");
    // /platform/page/main/main.jsp(192,4) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f9.setType("main");
    int _jspx_eval_eap_005flanguage_005f9 = _jspx_th_eap_005flanguage_005f9.doStartTag();
    if (_jspx_th_eap_005flanguage_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f9);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f9);
    return false;
  }
}
