/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2015-05-29 03:44:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.platform.page.system.widgets;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class defIconCls_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<div id=\"defTradeIconClsMenu\" class=\"easyui-menu\" style=\"width:120px;\">\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<span>change icon</span>\r\n");
      out.write("\t\t<div class=\"menu-content\" style=\"text-align:left;padding:10px\">\r\n");
      out.write("\t\t\t<div style=\"font-weight:bold;font-size:16px\">please select icon:</div>\r\n");
      out.write("\t\t\t<div class='defTradeIconCls'>\r\n");
      out.write("\t\t\t\t<div class='defTradeIconClsArea' refCls='icon-impCredit'>\r\n");
      out.write("\t\t\t\t\t<div class='defIconCls icon-impCredit' ></div>\r\n");
      out.write("\t\t\t\t\t<div class='defIconClsText'>icon-impCredit</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class='defTradeIconClsArea' refCls='icon-1'>\r\n");
      out.write("\t\t\t\t\t<div class='defIconCls icon-1' ></div>\r\n");
      out.write("\t\t\t\t\t<div class='defIconClsText'>icon-1</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class='defTradeIconClsArea' refCls='icon-2'>\r\n");
      out.write("\t\t\t\t\t<div class='defIconCls icon-2'></div>\r\n");
      out.write("\t\t\t\t\t<div class='defIconClsText'>icon-2</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class='defTradeIconClsArea' refCls='icon-im'>\r\n");
      out.write("\t\t\t\t\t<div class='defIconCls icon-im'></div>\r\n");
      out.write("\t\t\t\t\t<div class='defIconClsText'>icon-im</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class='defTradeIconClsArea' refCls='icon-ex'>\r\n");
      out.write("\t\t\t\t\t<div class='defIconCls icon-ex'></div>\r\n");
      out.write("\t\t\t\t\t<div class='defIconClsText'>icon-ex</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class='defTradeIconClsArea' refCls='icon-nt'>\r\n");
      out.write("\t\t\t\t\t<div class='defIconCls icon-nt'></div>\r\n");
      out.write("\t\t\t\t\t<div class='defIconClsText'>icon-nt</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class='defTradeIconClsArea' refCls='icon-fi'>\r\n");
      out.write("\t\t\t\t\t<div class='defIconCls icon-fi'></div>\r\n");
      out.write("\t\t\t\t\t<div class='defIconClsText'>icon-fi</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class='defTradeIconClsArea' refCls='icon-mt'>\r\n");
      out.write("\t\t\t\t\t<div class='defIconCls icon-mt'></div>\r\n");
      out.write("\t\t\t\t\t<div class='defIconClsText'>icon-mt</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class='defTradeIconClsArea' refCls='icon-mt700'>\r\n");
      out.write("\t\t\t\t\t<div class='defIconCls icon-mt700'></div>\r\n");
      out.write("\t\t\t\t\t<div class='defIconClsText'>icon-mt700</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\t\t\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("/*\r\n");
      out.write("    $.parser.parse($(\"#defTradeIconClsMenu\"));\r\n");
      out.write("    \r\n");
      out.write("\t//添加右键菜单事件\r\n");
      out.write("\t$('.defMasterMenuIconAreaWrap').bind('contextmenu.xcpApp',function(e){\r\n");
      out.write("\t\tvar trade= $(e.target).closest('div.tradeIconArea');\r\n");
      out.write("\t\tif(trade && trade.length >=1){\r\n");
      out.write("\t\t\tcurContextmenuTrade = trade;\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t$('#defTradeIconClsMenu').menu('show', {\r\n");
      out.write("\t\t\t\tleft: e.pageX,\r\n");
      out.write("\t\t\t\ttop : e.pageY\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$('.defTradeIconClsArea').bind('click.xcpApp',function(e){\r\n");
      out.write("\t\t var refCls = $(this).attr('refCls');\r\n");
      out.write("\t\t if(refCls && curContextmenuTrade){\r\n");
      out.write("\t\t\t var  iconCls   =  curContextmenuTrade.attr('refIconCls'); \r\n");
      out.write("\t\t\t if(iconCls){\r\n");
      out.write("\t\t\t\t curContextmenuTrade.find('div.tradeIcon').removeClass(iconCls).addClass(refCls);\r\n");
      out.write("\t\t\t\t curContextmenuTrade.attr('refIconCls',refCls);\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t $('#defTradeIconClsMenu').menu('hide');\r\n");
      out.write("\t\t\t\t curContextmenuTrade = null;\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t }\r\n");
      out.write("\t});\r\n");
      out.write("*/\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
