/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2015-05-29 03:44:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.platform.page.system.widgets;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userSetting_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/eap.tld", Long.valueOf(1432547002277L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

Integer login = 0;
String printRole = "false";
if(request.getAttribute("login") != null){
	login = (Integer)request.getAttribute("login");
	if(login == 0){
		if(request.getAttribute("printRole") != null){
			printRole = (String)request.getAttribute("printRole");
		}
	}
} else {
	if(request.getAttribute("printRole") != null){
		printRole = (String)request.getAttribute("printRole");
	}
}

      out.write("\r\n");
      out.write("<div class=\"userSettingPanel\">\r\n");
      out.write("<div id=\"userSettingPanelLeft\" class='userSettingPanelLeft'>\r\n");
      out.write("\t<div class='leftIcon current' refRightIconId = \"rightIcon-1\">\r\n");
      out.write("\t\t<span >");
      if (_jspx_meth_eap_005flanguage_005f0(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<div  class='leftIcon ' refRightIconId = \"rightIcon-3\">\r\n");
      out.write("\t\t<span >");
      if (_jspx_meth_eap_005flanguage_005f1(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("\t</div> \r\n");
      out.write("\t<div  class='leftIcon ' refRightIconId = \"rightIcon-4\">\r\n");
      out.write("\t\t<span >");
      if (_jspx_meth_eap_005flanguage_005f2(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div  class='leftIcon ' refRightIconId = \"rightIcon-5\" ");
 if(!"true".equalsIgnoreCase(printRole)) out.print("style=\"display: none\""); 
      out.write(">\r\n");
      out.write("\t\t<span >");
      if (_jspx_meth_eap_005flanguage_005f3(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"userSettingPanelRight\" class=\"userSettingPanelRight\">\r\n");
      out.write("   <div  id='rightIcon-1' class='rightIcon current' >\r\n");
      out.write("   \t\t<span class='btn btnSpan' refMethod='language' refValue='zh_CN'>");
      if (_jspx_meth_eap_005flanguage_005f4(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("\t\t<span class='btn btnSpan' refMethod='language' refValue='en_US'>");
      if (_jspx_meth_eap_005flanguage_005f5(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("   </div>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("   <div  id='rightIcon-3' class='rightIcon' >\r\n");
      out.write("   \t\t<span class='btn btnSpan' refMethod=\"viewReportMethod\"  refValue=\"0\">");
      if (_jspx_meth_eap_005flanguage_005f6(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("\t\t<span class='btn btnSpan' refMethod=\"viewReportMethod\"  refValue=\"1\">");
      if (_jspx_meth_eap_005flanguage_005f7(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("   </div> \r\n");
      out.write("   <div  id='rightIcon-4' class='rightIcon' >\r\n");
      out.write("    \t<div >\r\n");
      out.write("    \t\t<div >\r\n");
      out.write("    \t\t\t<span style=\"width: 38%;\" class=\"btnSpan\">");
      if (_jspx_meth_eap_005flanguage_005f8(_jspx_page_context))
        return;
      out.write(" </span>\r\n");
      out.write("    \t\t\t<span style=\"width: 20%;\" class=\"btnSpan\">");
      if (_jspx_meth_eap_005flanguage_005f9(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("    \t\t\t<span style=\"width: 20%;\" class=\"btnSpan\">");
      if (_jspx_meth_eap_005flanguage_005f10(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class='divTab'></div>\r\n");
      out.write("    \t\t<div id = \"bingpUl\" style=\"height: 192px;overflow-y:auto;\" >\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t<span class='btn btnSpan' id=\"settingCon\" style='margin-top: 5px;'>");
      if (_jspx_meth_eap_005flanguage_005f11(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("   </div> \r\n");
      out.write("   <div  id='rightIcon-5' class='rightIcon' >\r\n");
      out.write("    \t<div >\r\n");
      out.write("    \t\t<!-- <div >style=\"background-color: #f1f1f8\"\r\n");
      out.write("    \t\t\t<span class=\"btnSpan\"> </span>\r\n");
      out.write("    \t\t</div> -->\r\n");
      out.write("    \t\t<div id = \"printSet\" style=\"height: 192px;overflow-y:auto;\" >\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t<span class='btn btnSpan' id=\"printSetting\" style='margin-top: 5px;'>");
      if (_jspx_meth_eap_005flanguage_005f12(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("   </div> \r\n");
      out.write("</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_eap_005flanguage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f0 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f0.setParent(null);
    // /platform/page/system/widgets/userSetting.jsp(22,9) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f0.setName("main.yuyxz");
    // /platform/page/system/widgets/userSetting.jsp(22,9) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f0.setType("main");
    int _jspx_eval_eap_005flanguage_005f0 = _jspx_th_eap_005flanguage_005f0.doStartTag();
    if (_jspx_th_eap_005flanguage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f0);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f1 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f1.setParent(null);
    // /platform/page/system/widgets/userSetting.jsp(28,9) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f1.setName("main.chakmhms");
    // /platform/page/system/widgets/userSetting.jsp(28,9) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f1.setType("main");
    int _jspx_eval_eap_005flanguage_005f1 = _jspx_th_eap_005flanguage_005f1.doStartTag();
    if (_jspx_th_eap_005flanguage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f1);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f2 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f2.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f2.setParent(null);
    // /platform/page/system/widgets/userSetting.jsp(31,9) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f2.setName("main.kuaislsz");
    // /platform/page/system/widgets/userSetting.jsp(31,9) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f2.setType("main");
    int _jspx_eval_eap_005flanguage_005f2 = _jspx_th_eap_005flanguage_005f2.doStartTag();
    if (_jspx_th_eap_005flanguage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f2);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f3 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f3.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f3.setParent(null);
    // /platform/page/system/widgets/userSetting.jsp(34,9) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f3.setName("main.printSetting");
    // /platform/page/system/widgets/userSetting.jsp(34,9) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f3.setType("main");
    int _jspx_eval_eap_005flanguage_005f3 = _jspx_th_eap_005flanguage_005f3.doStartTag();
    if (_jspx_th_eap_005flanguage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f3);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f4 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f4.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f4.setParent(null);
    // /platform/page/system/widgets/userSetting.jsp(40,69) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f4.setName("main.zhongw");
    // /platform/page/system/widgets/userSetting.jsp(40,69) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f4.setType("main");
    int _jspx_eval_eap_005flanguage_005f4 = _jspx_th_eap_005flanguage_005f4.doStartTag();
    if (_jspx_th_eap_005flanguage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f4);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f5 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f5.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f5.setParent(null);
    // /platform/page/system/widgets/userSetting.jsp(41,66) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f5.setName("main.yingw");
    // /platform/page/system/widgets/userSetting.jsp(41,66) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f5.setType("main");
    int _jspx_eval_eap_005flanguage_005f5 = _jspx_th_eap_005flanguage_005f5.doStartTag();
    if (_jspx_th_eap_005flanguage_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f5);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f6 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f6.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f6.setParent(null);
    // /platform/page/system/widgets/userSetting.jsp(49,74) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f6.setName("main.tabyq");
    // /platform/page/system/widgets/userSetting.jsp(49,74) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f6.setType("main");
    int _jspx_eval_eap_005flanguage_005f6 = _jspx_th_eap_005flanguage_005f6.doStartTag();
    if (_jspx_th_eap_005flanguage_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f6);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f7 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f7.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f7.setParent(null);
    // /platform/page/system/widgets/userSetting.jsp(50,71) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f7.setName("main.tanc");
    // /platform/page/system/widgets/userSetting.jsp(50,71) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f7.setType("main");
    int _jspx_eval_eap_005flanguage_005f7 = _jspx_th_eap_005flanguage_005f7.doStartTag();
    if (_jspx_th_eap_005flanguage_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f7);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f8 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f8.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f8.setParent(null);
    // /platform/page/system/widgets/userSetting.jsp(55,49) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f8.setName("main.quicTask");
    // /platform/page/system/widgets/userSetting.jsp(55,49) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f8.setType("main");
    int _jspx_eval_eap_005flanguage_005f8 = _jspx_th_eap_005flanguage_005f8.doStartTag();
    if (_jspx_th_eap_005flanguage_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f8);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f9 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f9.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f9.setParent(null);
    // /platform/page/system/widgets/userSetting.jsp(56,49) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f9.setName("main.quickBar");
    // /platform/page/system/widgets/userSetting.jsp(56,49) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f9.setType("main");
    int _jspx_eval_eap_005flanguage_005f9 = _jspx_th_eap_005flanguage_005f9.doStartTag();
    if (_jspx_th_eap_005flanguage_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f9);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f9);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f10 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f10.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f10.setParent(null);
    // /platform/page/system/widgets/userSetting.jsp(57,49) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f10.setName("main.theMainInter");
    // /platform/page/system/widgets/userSetting.jsp(57,49) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f10.setType("main");
    int _jspx_eval_eap_005flanguage_005f10 = _jspx_th_eap_005flanguage_005f10.doStartTag();
    if (_jspx_th_eap_005flanguage_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f10);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f10);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f11 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f11.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f11.setParent(null);
    // /platform/page/system/widgets/userSetting.jsp(63,72) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f11.setName("main.shezqr");
    // /platform/page/system/widgets/userSetting.jsp(63,72) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f11.setType("main");
    int _jspx_eval_eap_005flanguage_005f11 = _jspx_th_eap_005flanguage_005f11.doStartTag();
    if (_jspx_th_eap_005flanguage_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f11);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f11);
    return false;
  }

  private boolean _jspx_meth_eap_005flanguage_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eap:language
    com.ebills.web.LanguageTag _jspx_th_eap_005flanguage_005f12 = (com.ebills.web.LanguageTag) _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.get(com.ebills.web.LanguageTag.class);
    _jspx_th_eap_005flanguage_005f12.setPageContext(_jspx_page_context);
    _jspx_th_eap_005flanguage_005f12.setParent(null);
    // /platform/page/system/widgets/userSetting.jsp(74,74) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f12.setName("main.shezqr");
    // /platform/page/system/widgets/userSetting.jsp(74,74) name = type type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eap_005flanguage_005f12.setType("main");
    int _jspx_eval_eap_005flanguage_005f12 = _jspx_th_eap_005flanguage_005f12.doStartTag();
    if (_jspx_th_eap_005flanguage_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f12);
      return true;
    }
    _005fjspx_005ftagPool_005feap_005flanguage_0026_005ftype_005fname_005fnobody.reuse(_jspx_th_eap_005flanguage_005f12);
    return false;
  }
}
